repository:
  name: ingeno-standard-ts
  description: Ingeno TypeScript style guide, with linter, formatter and automatic code fixer, inspired by [StandardJS](https://standardjs.com/).
  topics: typescript, linter, standard
  default_branch: main
  allow_auto_merge: true
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: bug
    description: Something is broken
    color: '#CC0000'
  - name: chore
    color: '#f2df8c'
    description: Repository or code maintenance
  - name: documentation
    color: '#1D76DB'
    description: Change in the documentation
  - name: dependencies
    color: '#70f9e0'
    description: Update dependencies
  - name: feature
    description: New feature or change to an existing feature
    color: '#1B003F'

collaborators:
  - username: johnmartel
    permission: admin

teams:
  - name: admins
    permission: admin
  - name: ingeno
    permission: push

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_signatures: true
      restrictions: null
