on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - name: Package code
        run: npm pack
      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.tgz
          token: ${{ secrets.GITHUB_TOKEN }}
